steps:
- id: 'dep-ensure'
  name: 'gcr.io/cloud-builders/glide'
  env: ['PROJECT_ROOT=github.com/orangesys/orangeapi']
  args: ['install']

- id: 'build-tag'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/orangeapi', '.']
  waitFor: ['dep-ensure']