steps:
- id: 'dep-ensure'
  name: 'gcr.io/cloud-builders/glide'
  env: ['PROJECT_ROOT=github.com/orangesys/orangeapi']
  args: ['install']
- id: 'build-tag'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/orangeapi:$TAG_NAME', '.']
- id: 'push'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/orangeapi:$TAG_NAME']