steps:
- id: 'make-dep'
  name: 'golang:1.8.3'
  args: ['make', 'deps']

- id: 'build-tag'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/orangeapi', '.']
  waitFor: ['make-dep']