steps:
- id: 'dep-ensure'
  name: 'gcr.io/saas-orangesys-io/dep:82b7fa94-a585-45a0-9f65-09e21393bc7a'
  env: ['GOPATH=.']
  args: ['ensure']

- id: 'build-tag'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/orangeapi', '.']
  waitFor: ['dep-ensure']