version: 2

references:
  container_config: &container_config
    docker:
      - image: golang:1.8.3
    working_directory: /go/src/github.com/orangesys/orangeapi

    workspace_root: &workspace_root
      /tmp/workspace

    attach_workspace: &attach_workspace
      attach_workspace:
        at: *workspace_root

    load_code: &load_code
      run:
        name: load code from workspace
        command: |
          # Move all files and dotfiles to current directory
          mv /tmp/workspace/orangeapi/* /tmp/workspace/orangeapi/.[!.]* .
    go_cache_key: &go_cache_key
      key: dependency-go-{{ checksum "glide.lock" }}

jobs:
  build_orangeapi:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: download dependencies
          command: |
            curl https://glide.sh/get | sh
            glide install
      - run:
          name: unit test
          command: |
            go test -v ./pkg/...
      - run:
          command: make build
      - run:
          command: |
            mkdir -p /tmp/workspace/orangeapi
            mv * .[!.]* /tmp/workspace/orangeapi/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - orangeapi

  build_container:
    <<: *container_config
    steps:
      - *attach_workspace
      - *load_code
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/alpine-orangeapi.tar
      - run:
          name: Install docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp/ -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build orangeapi Docker images
          command: |
            set +o pipefail
            ./scripts/create-container.sh
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/alpine-orangeapi.tar

  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/orangeapi
    environment:
      PROJECT_NAME: saas-orangesys-io
      CLUSTER_NAME: orangesys-io
      CLOUDSDK_COMPUTE_ZONE: asia-northeast1-c
      ORG_PATH: "github.com/orangesys"
      REPO_PATH: "${ORG_PATH}/orangeapi"
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/alpine-orangeapi.tar
      - run:
          name: Install docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp/ -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/alpine-orangeapi.tar | true
            docker images
      - run:
          name: Push docker hub and gcloud
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ${HOME}/account-auth.json
            gcloud auth activate-service-account --key-file ${HOME}/account-auth.json
            gcloud config set project $PROJECT_NAME
            gcloud --quiet config set container/cluster $CLUSTER_NAME
            gcloud --quiet container clusters get-credentials $CLUSTER_NAME
            ./scripts/push-container-images.sh
            curl -X POST https://hooks.microbadger.com/images/orangesys/alpine-orangeapi/_24B4d4BBsQhsH6Av_nH1ZKsl2s=
      - run:
          name: Deploy to GKE
          command: |
            ./scripts/deploy.sh
            curl -s -S -X POST --data-urlencode "payload={'channel': '#ops', 'text': ':earth_asia: :fire: release $CIRCLE_PROJECT_REPONAME (TAG $CIRCLE_TAG) to GKE completed (build $CIRCLE_BUILD_NUM)' }" $SLACK_OPS >/dev/null
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_orangeapi:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/      
      - build_container:
          requires:
            - build_orangeapi
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/            
      - deploy:
          requires:
            - build_orangeapi
            - build_container
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/